[ids]
*

[main]
pageup = left
pagedown = right
capslock = layer(control)
leftalt  = layer(meta)
rightalt  = layer(meta)
leftmeta = layer(alt)
rightmeta = layer(alt)
leftmeta+leftshift+f23 = layer(alt)
calc = M-A-t
